version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brunos1212
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scrum
      - POSTGRES_HOST=db
    expose:
      - "5432"
    networks:
      - djangonetwork
  web:
    build: ../
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    environment:
      - DJANGO_SUPERUSER_USERNAME=demo
      - DJANGO_SUPERUSER_PASSWORD=test
      - DJANGO_SUPERUSER_EMAIL=demo@email.com
volumes:
  pg_data:
networks:
      djangonetwork:
          driver: bridge