version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brunos1212
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scrum
      - POSTGRES_HOST=db
    expose:
      - "5432"
    networks:
      - djangonetwork
  web:
    build: ../
    tty: true
    command: python ./manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - django_data:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetwork
    env_file: "env-file"
volumes:
  pg_data:
  django_data:
networks:
      djangonetwork:
          driver: bridge